### PR TITLE
Split stdio, use click I/O, exit non-zero.

### PR DESCRIPTION
**Pull request by 4kbyte**
Use stdout only for data output. Given that stdio has only two output streams, this makes the concession that informational logging goes to stderr. The advantage of this approach is that stdout can be redirected or piped for additional processing.

For example:

```
python diffsanity.py check test/data/simple/{src,dest} |
  tee checksums.txt &&
  sort checksums.txt | column --table > checksums.table.txt &&
  mv checksums.table.txt checksums.txt
```

<details>
<summary>... which uses `column` from util-linux with the following output.</summary>

```
/hello.txt                       |  746308829575e17c3331bbcb00c0898b  |  ('2024-05-14T04:47:08',  'hello.txt',                   '14')
/one/hello.txt                   |  746308829575e17c3331bbcb00c0898b  |  ('2024-05-14T04:47:08',  'hello.txt',                   '14')
/sub/shorter.txt                 |  3f52d078e6dbaa62fe5c1fe5dceafa5d  |  ('2024-05-14T04:47:08',  'shorter.txt',                 '36')
/two/a-much-longer-filename.txt  |  3f52d078e6dbaa62fe5c1fe5dceafa5d  |  ('2024-05-14T04:47:08',  'a-much-longer-filename.txt',  '36')
/two/more/src-only.txt           |  2ff66bc28e8ac8f8a6c14a41bec9a2d1  |  ('2024-05-14T04:47:08',  'src-only.txt',                '62')
```

To undo padding when processing such a file:

```python
import csv
import re
with open("checksums.txt") as fd:
    reader = csv.reader(fd, delimiter="|", quoting=csv.QUOTE_NONE)
    [[re.sub(" +", " ", cell.strip()) for cell in row] for row in reader]
```
</details>

(The use of a file in this example, instead of piping directly, is to avoid sorting on the very large datasets typical of diffsanity.)

I'm not an advocate for using `click` inside the function--it belongs at the edges--but consistency is important both in terms of semantics and user experience. And for testing, which must be a bug in `click.testing` where stderr is empty except for `click.echo(..., err=True)`.

Finally, use a non-zero exit code on a failed diff.

Along the way, add code coverage and an integration test.

### CODE REVIEW

**Comment by 4kbyte** [comment]
An alternative to click I/O would be global functions named `out`, `err`, and `info`.

(The `logging` is better suited for services than command-line applications.)

**Comment by amontalenti** [comment]
This looks great. Thanks for this. Will play around with it a little in the next few days.

**Comment by amontalenti** [comment]
Overall this looks great. Trying out the code locally now, I suspect to merge quickly.

**Comment by amontalenti** [comment]
Just reviewed in GitHub Codespace and it looks good. Merging.

**Pull request merged**
